/*
// Compared the proto file used in PersonV1, this one has the following changes:
// 1. Change the order of id and name;
// 2. Remove optional address;
// 3. Add new PhoneType;

syntax = "proto2";

message Person {
    required int32 id = 2;
    required string name = 1;
    optional string email = 3;
    //optional string address = 4;

    enum PhoneType {
        MOBILE = 0;
        HOME = 1;
        WORK = 2;
        OFFICE = 3;
    }

    message PhoneNumber {
        required string number = 1;
        optional PhoneType type = 2 [default = HOME];
    }

    repeated PhoneNumber phone = 5;
}

// https://developers.google.cn/protocol-buffers/docs/overview
*/

namespace PersonV2
{
    // Generated by [protogen](https://protogen.marcgravell.com/)

    // This file was generated by a tool; you should avoid making direct changes.
    // Consider using 'partial classes' to extend these types
    // Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
    [global::ProtoBuf.ProtoContract()]
    public partial class Person : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"id", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"email")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Email
        {
            get { return __pbn__Email ?? ""; }
            set { __pbn__Email = value; }
        }
        public bool ShouldSerializeEmail() => __pbn__Email != null;
        public void ResetEmail() => __pbn__Email = null;
        private string __pbn__Email;

        [global::ProtoBuf.ProtoMember(5, Name = @"phone")]
        public global::System.Collections.Generic.List<PhoneNumber> Phones { get; } = new global::System.Collections.Generic.List<PhoneNumber>();

        [global::ProtoBuf.ProtoContract()]
        public partial class PhoneNumber : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"number", IsRequired = true)]
            public string Number { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"type")]
            [global::System.ComponentModel.DefaultValue(Person.PhoneType.Home)]
            public Person.PhoneType Type
            {
                get { return __pbn__Type ?? Person.PhoneType.Home; }
                set { __pbn__Type = value; }
            }
            public bool ShouldSerializeType() => __pbn__Type != null;
            public void ResetType() => __pbn__Type = null;
            private Person.PhoneType? __pbn__Type;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum PhoneType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MOBILE")]
            Mobile = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"HOME")]
            Home = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"WORK")]
            Work = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"OFFICE")]
            Office = 3,
        }

    }

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
}
