################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

message(">> Hello, libzmq")

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_LIBZMQ "libzmq")
    if (PC_LIBZMQ_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_LIBZMQ_CFLAGS} ${PC_LIBZMQ_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_LIBZMQ_INCLUDE_HINTS ${PC_LIBZMQ_INCLUDE_DIRS} ${PC_LIBZMQ_INCLUDE_DIRS}/*)
        set(PC_LIBZMQ_LIBRARY_HINTS ${PC_LIBZMQ_LIBRARY_DIRS} ${PC_LIBZMQ_LIBRARY_DIRS}/*)
    endif(PC_LIBZMQ_FOUND)
endif (NOT MSVC)

find_path (
    LIBZMQ_INCLUDE_DIRS
    NAMES zmq.h
    HINTS ${PC_LIBZMQ_INCLUDE_HINTS}
)

# When built as a static library, libzmq will set an additional
# compiler flag `-DZMQ_STATIC` through `set_target_properties`.
# (libzmq/CMakeLists.txt)
#
# Since we did not use `find_package` + `target_link_libraries`
# here, we must define `ZMQ_STATIC` manually. Otherwise, all
# function declarations in `zmq.h` will have a `__declspec(dllimport)`
# specifier. 
if (CZMQ_BUILD_STATIC)
    add_definitions(-DZMQ_STATIC=1)
endif ()

if (NOT MSVC)
    find_library (
        LIBZMQ_LIBRARIES
        NAMES zmq
        HINTS ${PC_LIBZMQ_LIBRARY_HINTS}
    )
else ()
    # libzmq dll/lib built with MSVC is named using the Boost convention.
    # https://github.com/zeromq/czmq/issues/577
    # https://bitbucket.org/ignitionrobotics/ign-transport/pull-requests/19/detec-zmq-under-windows-using-a-findzmq/diff
    # https://github.com/zeromq/libzmq/blob/master/CMakeLists.txt
    if (MSVC_IDE)
        set(MSVC_TOOLSET "-${CMAKE_VS_PLATFORM_TOOLSET}")
    else ()
        set(MSVC_TOOLSET "")
    endif ()

    set(_zmq_versions
        "4_3_1"
        "4_3_0"
        "4_2_5"
        "4_2_4"
        "4_2_3"
        "4_2_2"
        "4_2_1"
        "4_2_0"
        "4_0_4"
        "4_0_3"
        "4_0_2"
        "4_0_1"
        "4_0_0"
        "3_2_5"
        "3_2_4"
        "3_2_3"
        "3_2_2"
        "3_2_1"
        "3_2_0"
        "3_1_0")

    set(_zmq_debug_names)
    set(_zmq_release_names)

    foreach(ver ${_zmq_versions})
        list(APPEND _zmq_debug_names
            "libzmq${MSVC_TOOLSET}-mt-gd-${ver}" # Debug, BUILD_SHARED
            "libzmq${MSVC_TOOLSET}-mt-sgd-${ver}" # Debug, BUILD_STATIC
        )

        list(APPEND _zmq_release_names
            "libzmq${MSVC_TOOLSET}-mt-${ver}" # Release|RelWithDebInfo|MinSizeRel, BUILD_SHARED
            "libzmq${MSVC_TOOLSET}-mt-s-${ver}" # Release|RelWithDebInfo|MinSizeRel, BUILD_STATIC
        ) 
    endforeach()

    #message(">> ${_zmq_debug_names}")
    #message(">> ${_zmq_release_names}")

    find_library (ZeroMQ_LIBRARY_DEBUG
        NAMES zmq libzmq ${_zmq_debug_names}
    )

    find_library (ZeroMQ_LIBRARY_RELEASE
        NAMES zmq libzmq ${_zmq_release_names}
    )

    if (ZeroMQ_LIBRARY_RELEASE AND ZeroMQ_LIBRARY_DEBUG)
        set(LIBZMQ_LIBRARIES
            debug ${ZeroMQ_LIBRARY_DEBUG}
            optimized ${ZeroMQ_LIBRARY_RELEASE}
        )
    elseif (ZeroMQ_LIBRARY_RELEASE)
        set(LIBZMQ_LIBRARIES ${ZeroMQ_LIBRARY_RELEASE})
    elseif (ZeroMQ_LIBRARY_DEBUG)
        set(LIBZMQ_LIBRARIES ${ZeroMQ_LIBRARY_DEBUG})
    endif ()

    #file(STRINGS "${LIBZMQ_INCLUDE_DIRS}/zmq.h" _version_lines
    #    REGEX "^#define.ZMQ_VERSION_(MAJOR|MINOR|PATCH).([0-9]+$)")
    #message(">> ${_version_lines}")
endif ()

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    LIBZMQ
    REQUIRED_VARS LIBZMQ_LIBRARIES LIBZMQ_INCLUDE_DIRS
)
mark_as_advanced(
    LIBZMQ_FOUND
    LIBZMQ_LIBRARIES LIBZMQ_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

# References:
# https://github.com/zeromq/libzmq/issues/3318
# https://github.com/zeromq/czmq/issues/577
# https://stackoverflow.com/questions/31565788/cmake-find-library-with-version-number
# https://github.com/zeromq/libzmq/issues/2333
# https://bitbucket.org/ignitionrobotics/ign-transport/pull-requests/19/detec-zmq-under-windows-using-a-findzmq/diff
