// 2015-01-21T10:40+08:00
// Generating an UUID with Boost.Uuid or Azure's builtin UUID library.

#define USING_BOOST_UUID_LIBRARY
#define USING_AZURE_UUID_LIBRARY

#ifdef USING_BOOST_UUID_LIBRARY
# include <iostream>
# include <string>

# include <boost/uuid/uuid.hpp>
# include <boost/uuid/uuid_generators.hpp>
# include <boost/uuid/uuid_io.hpp>
#endif

#ifdef USING_AZURE_UUID_LIBRARY
# include <wascore/basic_types.h>

# ifdef _MSC_VER
#  pragma comment(lib, "wastorage.lib")
# endif
#endif

#ifdef _MSC_VER
# ifdef NDEBUG
#  define PAUSE() (__noop)
# else
#  include <cstdlib>
#  define PAUSE() std::system("pause")
# endif
#else
# define PAUSE() ((void)0)
#endif

int main()
{
#ifdef USING_BOOST_UUID_LIBRARY
    std::wstring uuidByBoost = boost::uuids::to_wstring(boost::uuids::random_generator()());
    std::wcout << L"UUID generated by Boost: " << uuidByBoost << std::endl;
#endif

#ifdef USING_AZURE_UUID_LIBRARY
    utility::string_t uuidByAzure = utility::uuid_to_string(utility::new_uuid());
    ucout << U("UUID generated by Azure: ") << uuidByAzure << std::endl;
#endif

    PAUSE();
    return 0;
}

// References:
// [Boost.Uuid](http://www.boost.org/doc/libs/1_57_0/libs/uuid/uuid.html)